=== ShilovIlya/EPAM_HomeWorks/HomeWork/out/production/HomeWork/javase13/t01/home_library.xsd
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://homework.ru/home_library"
        >


    <xs:element name="home_library" type="home_library_type"/>

    <xs:complexType name="home_library_type">
        <xs:sequence>
            <xs:element name="authors" type="authors_type"/>
            <xs:element name="books" type="books_type"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="authors_type">
        <xs:sequence>
            <xs:element name="author" type="author_type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="author_type">
        <xs:sequence>
            <xs:element name="author_name" type="author_name_type"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:simpleType name="author_name_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="w\.w\.w+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="books_type">
        <xs:sequence>
            <xs:element name="book" type="book_type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="book_type">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="id_author" type="xs:int"/>
            <xs:element name="genre" type="genre_type"/>
            <xs:element name="publish_year" type="xs:int"
                     minOccurs = "868" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="language" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="genre_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="novel"/>
            <xs:enumeration value="poem"/>
            <xs:enumeration value="drama"/>
            <xs:enumeration value="fable"/>
            <xs:enumeration value="short story"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== ShilovIlya/EPAM_HomeWorks/HomeWork/out/production/HomeWork/javase13/t01/home_library.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<home_library
        xmlns="http://homework.ru/home_library"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://homework.ru/home_library home_library.xsd">
    <authors>
        <author id="a1">
            <author_name>A.S.Pushkin</author_name>
            <country>Russia</country>
        </author>
        <author id="a2">
            <author_name>F.M.Dostoyevsky</author_name>
            <country>Russia</country>
        </author>
    </authors>
    <books>
        <book language="ru" id="b1">
            <name>Ruslan i Ludmila</name>
            <id_author>1</id_author>
            <genre>poem</genre>
            <publish_year>1980</publish_year>
        </book>
        <book language="ru" id="b2">
            <name>Malenkie tragedii</name>
            <id_author>1</id_author>
            <genre>drama</genre>
            <publish_year>1993</publish_year>
        </book>
        <book language="eng" id="b3">
            <name>Kapitanskay dochka</name>
            <id_author>1</id_author>
            <genre>novel</genre>
            <publish_year>1975</publish_year>
        </book>
    </books>
</home_library>
